version: '3.8'
services:
  anime-downloader:
    build: .
    container_name: Anime-Downloader
    ports:
      - "5555:5000"
    volumes:
      - ${DOWNLOADF}:/downloads   # Aqu√≠ DOWNLOADF es la ruta HOST
    environment:
      - DOWNLOAD_FOLDER=/downloads
      - PARALLEL_DOWNLOADS=${DOWNLOADS}
    restart: unless-stopped
